version: '2.20.2'
services:

  patientdb:
    container_name: patientdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: patientdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - 27018:27017
    extends:
      file: common-config.yml
      service: microservice-mongo-config

  configserver:
    image: "jcb826/healthcare-configserver:latest"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "jcb826/eurekaserver:latest"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  patient:
    image: "jcb826/patient:latest"
    container_name: patient-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "patient"
      SPRING_DATASOURCE_URL: "jdbc:mysql://patientdb:3306/patientdb"
    depends_on:
      patientdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  diabete-scoring:
    image: "jcb826/diabete-scoring:latest"
    container_name: diabete-scoring
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "diabete-scoring"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  note:
    image: "jcb826/note:latest"
    container_name: note
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "note"
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_HOST: "mongodb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  web-app:
    image: "jcb826/web-app:latest"
    container_name: web-app
    ports:
      - "9010:9010"
    environment:
      SPRING_APPLICATION_NAME: "web-app"
      SPRING_MVC_FORMAT_DATE: yyyy-MM-dd
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  healthcare:
    driver: "bridge"