version: "2.20.2"

services:
  configserver-b2x:
    image: siferga/configserver-b2x:latest
    container_name: configserver-b2x
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    #    extends:
    #      file: common-config.yml
    #      service: microservise-base-config
    networks:
      - b2x-network

  eurekaserver-b2x:
    image: siferga/eurekaserver-b2x:latest
    container_name: eurekaserver-b2x
    ports:
      - "8070:8070"
    depends_on:
      configserver-b2x:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    #    extends:
    #      file: common-config.yml
    #      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: ""
    networks:
      - b2x-network-network

#  mysql:
#    container_name: "healthcare"
#    image: mysql
#    environment:
#      MYSQL_DATABASE: db
#      MYSQL_ROOT_USERNAME: root
#      MYSQL_ROOT_PASSWORD: root
#    healthcheck:
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#      timeout: 20s
#      retries: 10
#    ports:
#      - 3307:3306
#    networks:
#      - b2x-network-network

#  webapp:
#    image: siferga/webapp-b2x
#    container_name: webapp-b2x
#    ports:
#      - "9010:9010"
#    depends_on:
#      configserver-b2x:
#        condition: service_healthy
#    #    extends:
#    #      file: common-config.yml
#    #      service: microservice-configserver-config
#    environment:
#      SPRING_APPLICATION_NAME: "webapp"
#    networks:
#      - bx2-network
#networks:
#  bx2-network:
