server:
  port: 8080
spring:
  application:
    name: "collaborator"
  datasource:
    url: jdbc:mysql://localhost:3309/collaboratordb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

#configration of actuator enpoint in eureka making info visible in eureka dashboard
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

#info in eureka server dashboard
info:
  app:
    name: "collaborator"
    description: "Collaborator Application"
    version: "1.0.0"

