server:
  port:
    9000
#Config General
spring:
  application:
    name: collaborator

  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/collaboratordb?createDatabaseIfNotExist= true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
#  config:
#    import: optional:configserver-b2x:https://localhost:8071/
#Configuration EUREKA CLIENT
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka

#Configuration de l'affichage des info
info:
  app:
    name: "Collaborator"
    description: "b2x app"
    version: "1.0.0"

