server:
  port:
    9020
#Config General
spring:
  application:
    name: project-b2x

  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3309/collaboratordb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: optional:configserver:https://localhost:8071/

#Configuration EUREKA CLIENT
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka

#Configuration de l'affichage des info
info:
  app:
    name: "Project"
    description: "b2x app"
    version: "1.0.0"


