server:
  port: 9010
spring:
  application:
    name: "webapp"
#  profiles:
#    active: "prod"
  mvc:
      format:
        date: yyyy-MM-dd

#  config:
#    import: "optional:configserver:http://localhost:8071/"



  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

#configration of actuator enpoint in eureka making info visible in eureka dashboard
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/



#info in eureka server dashboard
info:
  app:
    name: "webapp"
    description: "webapp Application"
    version: "1.0.0"




